### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jurasofish** [jlowin/fastmcp#30]
Hey! Awesome project, I am literally in the middle of building something pretty much the same as this - but this is better. I'd love to take my efforts and incorporate them into this project. Are you open to contributions? 

Some things I'd love to add immediately
- [ ] strict mypy
- [ ] Clear docs on logging - since the MCP server runs in the background it's nice to log to a file you can tail, having a nice recipe for this in the docs would be great
- [ ] Ability to have the server log every request and response so you can watch things as they happen
- [x] (#31) Ensure use of `x: Annotated[int, Field(description="...")]` results in the description in the json schema (looks like it already does but just needs some tests)
- [x] (#31) Handle complex inputs like `x: list[int]`, `x: list[str] | str | None`, `x: MyModel` - this is actually hard because at least with claude desktop it seems unable to output anything other than an object mapping from string to string/float/number  - so lists/nulls/sub-models end up output as json strings and thus fail validation. I have code that does this that I can contribute, I can see how it would fit into FastMCP without much trouble, just need to rework the use of validate_call
- [x] (#31) Handle things like `x: Annotated[int, Field(1)]\n y: int` so like required arg after one with a "default" via pydantic's Field.
- [x] (#31) Remove context items from the generated JSON schema

less critical things
- docs on how to test tools/resources/etc with FastMCP
- middleware, to inject things into requests/responses. For example, I might like to inject into every response how many characters are in it. Or I might like to transform certain inputs before they're handled for all tools. Possibly overkill
- maybe dependency injection. Handy for testing (better typing than overriding env vars), handy in cases where various args need to validate things against some common state. Possibly overkill

**Comment by jlowin** [comment]
@jurasofish that all sounds awesome! Would welcome contributions.

I actually didn’t look closely enough to realize that the input spec was so limited and would love to expand it. ControlFlow may have some [helpful code](https://github.com/PrefectHQ/ControlFlow/blob/f259fa8144ed31b8bde5902a2de8548dd4601ce5/src/controlflow/tools/tools.py#L108), though it doesn’t have the issue of non-structured inputs.
